from enum import StrEnum
class RiskLevel(StrEnum):
    PASSIVE="PASSIVE"; LOW_IMPACT="LOW_IMPACT"; ACTIVE="ACTIVE"; HIGH_IMPACT="HIGH_IMPACT"
class EvidenceState(StrEnum):
    OBSERVED="OBSERVED"; POTENTIAL="POTENTIAL"; LIKELY="LIKELY"; CONFIRMED="CONFIRMED"; NOT_REPRODUCED="NOT_REPRODUCED"
